name: Build & Push to Internal Registry

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, k3s]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: echo "TAG=registry.localhost/magiclens:v0.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Login to internal registry (se necessário)
        run: echo "sem login, registry é aberto"

      - name: Build Docker image
        run: docker build -t $TAG .

      - name: Push to registry
        run: docker push $TAG

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Generate manifest
        run: envsubst < k8s/deployment.yaml.template > k8s/deployment.yaml

      - name: Deploy to cluster
        run: kubectl apply -f k8s/